# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.28.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.28.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chuckzumbaugh/Documents/kaliedoscope

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chuckzumbaugh/Documents/kaliedoscope

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.28.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.28.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chuckzumbaugh/Documents/kaliedoscope/CMakeFiles /Users/chuckzumbaugh/Documents/kaliedoscope//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chuckzumbaugh/Documents/kaliedoscope/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kaliedoscope

# Build rule for target.
kaliedoscope: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kaliedoscope
.PHONY : kaliedoscope

# fast build rule for target.
kaliedoscope/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/build
.PHONY : kaliedoscope/fast

AST_Nodes/BinaryExprAST.o: AST_Nodes/BinaryExprAST.cpp.o
.PHONY : AST_Nodes/BinaryExprAST.o

# target to build an object file
AST_Nodes/BinaryExprAST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/BinaryExprAST.cpp.o
.PHONY : AST_Nodes/BinaryExprAST.cpp.o

AST_Nodes/BinaryExprAST.i: AST_Nodes/BinaryExprAST.cpp.i
.PHONY : AST_Nodes/BinaryExprAST.i

# target to preprocess a source file
AST_Nodes/BinaryExprAST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/BinaryExprAST.cpp.i
.PHONY : AST_Nodes/BinaryExprAST.cpp.i

AST_Nodes/BinaryExprAST.s: AST_Nodes/BinaryExprAST.cpp.s
.PHONY : AST_Nodes/BinaryExprAST.s

# target to generate assembly for a file
AST_Nodes/BinaryExprAST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/BinaryExprAST.cpp.s
.PHONY : AST_Nodes/BinaryExprAST.cpp.s

AST_Nodes/CallExprAST.o: AST_Nodes/CallExprAST.cpp.o
.PHONY : AST_Nodes/CallExprAST.o

# target to build an object file
AST_Nodes/CallExprAST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/CallExprAST.cpp.o
.PHONY : AST_Nodes/CallExprAST.cpp.o

AST_Nodes/CallExprAST.i: AST_Nodes/CallExprAST.cpp.i
.PHONY : AST_Nodes/CallExprAST.i

# target to preprocess a source file
AST_Nodes/CallExprAST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/CallExprAST.cpp.i
.PHONY : AST_Nodes/CallExprAST.cpp.i

AST_Nodes/CallExprAST.s: AST_Nodes/CallExprAST.cpp.s
.PHONY : AST_Nodes/CallExprAST.s

# target to generate assembly for a file
AST_Nodes/CallExprAST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/CallExprAST.cpp.s
.PHONY : AST_Nodes/CallExprAST.cpp.s

AST_Nodes/ExprAST.o: AST_Nodes/ExprAST.cpp.o
.PHONY : AST_Nodes/ExprAST.o

# target to build an object file
AST_Nodes/ExprAST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/ExprAST.cpp.o
.PHONY : AST_Nodes/ExprAST.cpp.o

AST_Nodes/ExprAST.i: AST_Nodes/ExprAST.cpp.i
.PHONY : AST_Nodes/ExprAST.i

# target to preprocess a source file
AST_Nodes/ExprAST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/ExprAST.cpp.i
.PHONY : AST_Nodes/ExprAST.cpp.i

AST_Nodes/ExprAST.s: AST_Nodes/ExprAST.cpp.s
.PHONY : AST_Nodes/ExprAST.s

# target to generate assembly for a file
AST_Nodes/ExprAST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/ExprAST.cpp.s
.PHONY : AST_Nodes/ExprAST.cpp.s

AST_Nodes/FunctionAST.o: AST_Nodes/FunctionAST.cpp.o
.PHONY : AST_Nodes/FunctionAST.o

# target to build an object file
AST_Nodes/FunctionAST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/FunctionAST.cpp.o
.PHONY : AST_Nodes/FunctionAST.cpp.o

AST_Nodes/FunctionAST.i: AST_Nodes/FunctionAST.cpp.i
.PHONY : AST_Nodes/FunctionAST.i

# target to preprocess a source file
AST_Nodes/FunctionAST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/FunctionAST.cpp.i
.PHONY : AST_Nodes/FunctionAST.cpp.i

AST_Nodes/FunctionAST.s: AST_Nodes/FunctionAST.cpp.s
.PHONY : AST_Nodes/FunctionAST.s

# target to generate assembly for a file
AST_Nodes/FunctionAST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/FunctionAST.cpp.s
.PHONY : AST_Nodes/FunctionAST.cpp.s

AST_Nodes/NumberExprAST.o: AST_Nodes/NumberExprAST.cpp.o
.PHONY : AST_Nodes/NumberExprAST.o

# target to build an object file
AST_Nodes/NumberExprAST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/NumberExprAST.cpp.o
.PHONY : AST_Nodes/NumberExprAST.cpp.o

AST_Nodes/NumberExprAST.i: AST_Nodes/NumberExprAST.cpp.i
.PHONY : AST_Nodes/NumberExprAST.i

# target to preprocess a source file
AST_Nodes/NumberExprAST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/NumberExprAST.cpp.i
.PHONY : AST_Nodes/NumberExprAST.cpp.i

AST_Nodes/NumberExprAST.s: AST_Nodes/NumberExprAST.cpp.s
.PHONY : AST_Nodes/NumberExprAST.s

# target to generate assembly for a file
AST_Nodes/NumberExprAST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/NumberExprAST.cpp.s
.PHONY : AST_Nodes/NumberExprAST.cpp.s

AST_Nodes/PrototypeAST.o: AST_Nodes/PrototypeAST.cpp.o
.PHONY : AST_Nodes/PrototypeAST.o

# target to build an object file
AST_Nodes/PrototypeAST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/PrototypeAST.cpp.o
.PHONY : AST_Nodes/PrototypeAST.cpp.o

AST_Nodes/PrototypeAST.i: AST_Nodes/PrototypeAST.cpp.i
.PHONY : AST_Nodes/PrototypeAST.i

# target to preprocess a source file
AST_Nodes/PrototypeAST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/PrototypeAST.cpp.i
.PHONY : AST_Nodes/PrototypeAST.cpp.i

AST_Nodes/PrototypeAST.s: AST_Nodes/PrototypeAST.cpp.s
.PHONY : AST_Nodes/PrototypeAST.s

# target to generate assembly for a file
AST_Nodes/PrototypeAST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/PrototypeAST.cpp.s
.PHONY : AST_Nodes/PrototypeAST.cpp.s

AST_Nodes/VariableExprAST.o: AST_Nodes/VariableExprAST.cpp.o
.PHONY : AST_Nodes/VariableExprAST.o

# target to build an object file
AST_Nodes/VariableExprAST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/VariableExprAST.cpp.o
.PHONY : AST_Nodes/VariableExprAST.cpp.o

AST_Nodes/VariableExprAST.i: AST_Nodes/VariableExprAST.cpp.i
.PHONY : AST_Nodes/VariableExprAST.i

# target to preprocess a source file
AST_Nodes/VariableExprAST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/VariableExprAST.cpp.i
.PHONY : AST_Nodes/VariableExprAST.cpp.i

AST_Nodes/VariableExprAST.s: AST_Nodes/VariableExprAST.cpp.s
.PHONY : AST_Nodes/VariableExprAST.s

# target to generate assembly for a file
AST_Nodes/VariableExprAST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/AST_Nodes/VariableExprAST.cpp.s
.PHONY : AST_Nodes/VariableExprAST.cpp.s

lexer.o: lexer.cpp.o
.PHONY : lexer.o

# target to build an object file
lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/lexer.cpp.o
.PHONY : lexer.cpp.o

lexer.i: lexer.cpp.i
.PHONY : lexer.i

# target to preprocess a source file
lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/lexer.cpp.i
.PHONY : lexer.cpp.i

lexer.s: lexer.cpp.s
.PHONY : lexer.s

# target to generate assembly for a file
lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/lexer.cpp.s
.PHONY : lexer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/main.cpp.s
.PHONY : main.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kaliedoscope.dir/build.make CMakeFiles/kaliedoscope.dir/parser.cpp.s
.PHONY : parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kaliedoscope"
	@echo "... AST_Nodes/BinaryExprAST.o"
	@echo "... AST_Nodes/BinaryExprAST.i"
	@echo "... AST_Nodes/BinaryExprAST.s"
	@echo "... AST_Nodes/CallExprAST.o"
	@echo "... AST_Nodes/CallExprAST.i"
	@echo "... AST_Nodes/CallExprAST.s"
	@echo "... AST_Nodes/ExprAST.o"
	@echo "... AST_Nodes/ExprAST.i"
	@echo "... AST_Nodes/ExprAST.s"
	@echo "... AST_Nodes/FunctionAST.o"
	@echo "... AST_Nodes/FunctionAST.i"
	@echo "... AST_Nodes/FunctionAST.s"
	@echo "... AST_Nodes/NumberExprAST.o"
	@echo "... AST_Nodes/NumberExprAST.i"
	@echo "... AST_Nodes/NumberExprAST.s"
	@echo "... AST_Nodes/PrototypeAST.o"
	@echo "... AST_Nodes/PrototypeAST.i"
	@echo "... AST_Nodes/PrototypeAST.s"
	@echo "... AST_Nodes/VariableExprAST.o"
	@echo "... AST_Nodes/VariableExprAST.i"
	@echo "... AST_Nodes/VariableExprAST.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

